name: unit

on:
  push:
    branches: [main]
    paths:
      - "sdks/community/java/**"
      - ".github/workflows/unit-java-sdk.yml"
  pull_request:
    branches: [main]
    paths:
      - "sdks/community/java/**"
      - ".github/workflows/unit-java-sdk.yml"

permissions:
  contents: read

jobs:
  java:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sdks/community/java

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Run tests
        run: mvn -B -ntp test
