name: unit

on:
  push:
    branches: [main]
    paths:
      - "sdks/python/**"
      - ".github/workflows/unit-python-sdk.yml"
  pull_request:
    branches: [main]
    paths:
      - "sdks/python/**"
      - ".github/workflows/unit-python-sdk.yml"

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4.2.0
        with:
          version: ">=0.8.0"

      - name: Load cached venv
        id: cached-uv-dependencies
        uses: actions/cache@v4
        with:
          path: sdks/python/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('sdks/python/uv.lock') }}

      - name: Install dependencies
        working-directory: sdks/python
        run: uv sync

      - name: Run tests
        working-directory: sdks/python
        run: uv run python -m unittest discover tests -v
